# Generated by Django 4.2.27 on 2026-04-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_team'),
    ]

    operations = [
    ]
