# Generated by Django 4.2.27 on 2026-01-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not-started', 'Not Started'), ('pending', 'Pending'), ('completed', 'Completed')], default='not-started', max_length=20)),
                ('pinned', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='notes.note')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_shared_by_me', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_shared_with_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note Share',
                'verbose_name_plural': 'Note Shares',
                'db_table': 'note_shares',
                'unique_together': {('note', 'shared_with')},
            },
        ),
    ]
